version: '3.9'
services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/app
    volumes:
      - .:/app
